server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:larder}?currentSchema=user_service
    username: ${POSTGRES_USER:larder_app}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: user_service
