server:
  port: 8082

spring:
  application:
    name: inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:larder}?currentSchema=inventory_service
    username: ${POSTGRES_USER:larder_app}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: inventory_service
