server:
  port: 8084

spring:
  application:
    name: matching
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:larder}?currentSchema=matching_service
    username: ${POSTGRES_USER:larder_app}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: matching_service
